/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "sanctum.csrf-cookie": [],
    "health": [],
    "home": [],
    "dashboard": [],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "devices.index": [],
    "devices.create": [],
    "devices.store": [],
    "devices.show": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "devices.edit": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "devices.update": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "devices.destroy": [
        {
            "name": "device",
            "required": true,
            "binding": "id"
        }
    ],
    "failureTypes.index": [],
    "failureTypes.create": [],
    "failureTypes.store": [],
    "failureTypes.show": [
        {
            "name": "failureType",
            "required": true,
            "binding": "id"
        }
    ],
    "failureTypes.edit": [
        {
            "name": "failureType",
            "required": true,
            "binding": "id"
        }
    ],
    "failureTypes.update": [
        {
            "name": "failureType",
            "required": true,
            "binding": "id"
        }
    ],
    "failureTypes.destroy": [
        {
            "name": "failureType",
            "required": true,
            "binding": "id"
        }
    ],
    "maintenances.index": [],
    "maintenances.create": [],
    "maintenances.store": [],
    "maintenances.show": [
        {
            "name": "maintenance",
            "required": true,
            "binding": "id"
        }
    ],
    "maintenances.edit": [
        {
            "name": "maintenance",
            "required": true,
            "binding": "id"
        }
    ],
    "maintenances.update": [
        {
            "name": "maintenance",
            "required": true,
            "binding": "id"
        }
    ],
    "maintenances.destroy": [
        {
            "name": "maintenance",
            "required": true,
            "binding": "id"
        }
    ],
    "organizations.index": [],
    "organizations.create": [],
    "organizations.store": [],
    "organizations.show": [
        {
            "name": "organization",
            "required": true
        }
    ],
    "organizations.edit": [
        {
            "name": "organization",
            "required": true
        }
    ],
    "organizations.update": [
        {
            "name": "organization",
            "required": true
        }
    ],
    "organizations.destroy": [
        {
            "name": "organization",
            "required": true
        }
    ],
    "logs.index": [],
    "logs.show": [
        {
            "name": "log",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
